In [2]:
import numpy as np

## The Basics

In [19]:
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0, 8.2, 7.2], [1.5, 2.6, 5.5]])
print(b)

[[9.  8.2 7.2]
 [1.5 2.6 5.5]]


## Get Dimension


In [9]:
b.ndim

2

In [11]:
a.ndim

1

## Get Shape

In [14]:
a.shape

(3,)

In [16]:
b.shape

(2, 3)

## Get Type

In [20]:
a.dtype

dtype('int16')

## Get Size

In [23]:
a.itemsize

2

## Get total size

In [26]:
a.size

3

In [27]:
a.nbytes

6