# Math

In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])
print(a+b) # + - * / sin cos 等都可使用

[2 2 4 4]


## Linear Algebra

In [8]:
  a = np.ones((2, 3))
  b = np.full((3, 2), 2)
#   print(a*b) Error
np.matmul(a, b)


array([[6., 6.],
       [6., 6.]])

## Find the determinant

In [11]:
c = np.identity(2)
np.linalg.det(c)
# https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

1.0

## statistics

In [13]:
state = np.array([[1, 2, 3], [4, 5, 6]])
state

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.min(state)

1

In [16]:
np.min(state, axis=1) # 每一列作比較

array([1, 4])

In [17]:
np.min(state, axis=0) # 每一行做比較

array([1, 2, 3])

In [19]:
np.max(state)

6

In [21]:
np.sum(state)

21

In [22]:
np.sum(state, axis=0)

array([5, 7, 9])