# Miscellaneous

In [1]:
import numpy as np

In [6]:
data = np.genfromtxt('data.txt', delimiter=',').astype('int32') # 預設浮點數, 透過 astype 轉型, 會以複製方式
print(data)

[[ 1  2  3  4  5  6  7  8]
 [21 22 23 24 25 26 27 28]
 [31 32 33 34 35 36 37 38]
 [41 42 43 44 45 46 47 48]]


## Advanced Indexing and Boolean Masking

In [7]:
data > 30 # 多個條件也行得通

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [9]:
data[data > 30]

array([31, 32, 33, 34, 35, 36, 37, 38, 41, 42, 43, 44, 45, 46, 47, 48])

## You can index with a list in NumPY

In [16]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 3]]

array([2, 3, 4])

In [19]:
np.any(data > 23, axis=0) # 有符合其中一個

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [21]:
np.all(data > 23, axis=0) # 權要符合

array([False, False, False, False, False, False, False, False])

## Example

In [27]:
a = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25],
                [26, 27, 28, 29, 30]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [30]:
"""
取 [[11, 12]
    [16, 17]]
"""
a[2:4, 0:2]


array([[11, 12],
       [16, 17]])

In [32]:
"""
取 2, 8, 14 ,20 數值
"""
a[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [34]:
"""
取 
    4, 5
    24, 25
    29, 30
"""
a[[0, 4, 5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])