# Reorganizing Arrys

In [5]:
import numpy as np

In [7]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
print(before.shape)
print(before.ndim)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [9]:
after = before.reshape((8, 1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [12]:
after = before.reshape((2, 2, 2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Vertically stacking vectors

In [21]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack((v1, v2)) # 合併的 array 長度需相同

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
np.vstack((v1, v1, v2, v2))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

## Horizontal stack

In [25]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
print(h1)
print(h2)
np.hstack((h1, h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])