# Accessing/Changing specific element, rows, columns, etc

In [2]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [11, 22, 33, 44, 55, 66, 77]])
print(a)

[[ 1  2  3  4  5  6  7]
 [11 22 33 44 55 66 77]]


In [7]:
a.shape

(2, 7)

## Get a specific element [r, c]

In [10]:
a[1, 5]

66

In [12]:
a[1, -2] # 從後面數

66

## Get a specific row

In [15]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

## Get a specific column

In [17]:
a[:, 2] # : 所有 row, 第 2 column

array([ 3, 33])

## Getting a little more fancy \[startindex:endindex:stepsize\]

In [19]:
a[0, 1:6:2] # 第 0 row, 取 1 - 6 行，每 2 step 取一次值

array([2, 4, 6])

In [21]:
a[0, 1:-1:2]

array([2, 4, 6])

In [25]:
a[0, 3] = 100
print(a)
a[:, 2] = [100, 200]
print(a)

[[  1   2 100 100   5   6   7]
 [ 11  22 200  44  55  66  77]]
[[  1   2 100 100   5   6   7]
 [ 11  22 200  44  55  66  77]]


## 3-d Array Example

In [27]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Get specfic element

In [30]:
b[0, 1, 1]

4

In [37]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [39]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

## replace

In [42]:
b[:, 1, :] = [[100, 100], [200, 200]]
print(b)

[[[  1   2]
  [100 100]]

 [[  5   6]
  [200 200]]]
