# initializing Different Types of Arrays

In [2]:
import numpy as np

## All 0s matrix

In [4]:
np.zeros(5)
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## All 1s matrix

In [7]:
np.ones((2, 6), dtype='int16')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

## Any other number

In [10]:
np.full((2, 3, 3), 10) # 相同也可以指定 dtype

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

## Any other number (full_like)

In [15]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
np.full_like(a, 100)

array([[[100, 100, 100],
        [100, 100, 100]],

       [[100, 100, 100],
        [100, 100, 100]]])

## Random decimal numbers

In [19]:
np.random.rand(4, 5)

array([[0.19835153, 0.84762181, 0.44674559, 0.37291346, 0.58461994],
       [0.35347273, 0.12795274, 0.29410527, 0.96104322, 0.15632069],
       [0.09090067, 0.16259275, 0.69208239, 0.87858724, 0.40038079],
       [0.49784613, 0.65401389, 0.49552174, 0.79161899, 0.39979548]])

## Random Interget values

In [23]:
np.random.randint(8, size=(2, 2))
np.random.randint(4, 7, size=(2, 2)) # 4 - 7 的範圍，大小 2 * 2 

array([[5, 6],
       [4, 6]])

## The indentity matrix

In [25]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## Repeat an array

In [28]:
arr = np.array([100, 200, 300])
r1 = np.repeat(arr, 2)
print(r1)

[100 100 200 200 300 300]


In [31]:
arr = np.array([[100, 200, 300]])
r1 = np.repeat(arr, 2, axis=0)
print(r1)

[[100 200 300]
 [100 200 300]]


## Example 

In [36]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays

In [40]:
a = np.array([1, 2, 3])
b = a
b[0] = 100
print('a=', a)
print('b=', b)

# a b 都指向同一個記憶體位置, 解決方式因使用 copy function

a= [100   2   3]
b= [100   2   3]


In [41]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print('a=', a)
print('b=', b)


a= [1 2 3]
b= [100   2   3]
